image: node:15

services:
  - docker:dind

cache:
  paths:
    - node_modules/

stages:
  - test

test:
  stage: test
  before_script:
    - npm install
  script:
    - npm run test
  only:
    - branches